
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace MVP.gpCustom
{
	public abstract class _nsaPUC_GL10000 : SqlClientEntity
	{
		public _nsaPUC_GL10000()
		{
			this.QuerySource = "nsaPUC_GL10000";
			this.MappingName = "nsaPUC_GL10000";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_nsaPUC_GL10000LoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(string Nsa_Codigo)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.Nsa_Codigo, Nsa_Codigo);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_nsaPUC_GL10000LoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter Nsa_Nivel_Cuenta
			{
				get
				{
					return new SqlParameter("@Nsa_Nivel_Cuenta", SqlDbType.Char, 11);
				}
			}
			
			public static SqlParameter Nsa_Descripcion_Nivel
			{
				get
				{
					return new SqlParameter("@Nsa_Descripcion_Nivel", SqlDbType.Char, 101);
				}
			}
			
			public static SqlParameter Nsa_Codigo
			{
				get
				{
					return new SqlParameter("@Nsa_Codigo", SqlDbType.Char, 101);
				}
			}
			
			public static SqlParameter Nsa_Descripcion_Codigo
			{
				get
				{
					return new SqlParameter("@Nsa_Descripcion_Codigo", SqlDbType.Char, 101);
				}
			}
			
			public static SqlParameter DEX_ROW_ID
			{
				get
				{
					return new SqlParameter("@DEX_ROW_ID", SqlDbType.Int, 0);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string Nsa_Nivel_Cuenta = "nsa_Nivel_Cuenta";
            public const string Nsa_Descripcion_Nivel = "nsa_Descripcion_Nivel";
            public const string Nsa_Codigo = "nsa_Codigo";
            public const string Nsa_Descripcion_Codigo = "nsa_Descripcion_Codigo";
            public const string DEX_ROW_ID = "DEX_ROW_ID";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[Nsa_Nivel_Cuenta] = _nsaPUC_GL10000.PropertyNames.Nsa_Nivel_Cuenta;
					ht[Nsa_Descripcion_Nivel] = _nsaPUC_GL10000.PropertyNames.Nsa_Descripcion_Nivel;
					ht[Nsa_Codigo] = _nsaPUC_GL10000.PropertyNames.Nsa_Codigo;
					ht[Nsa_Descripcion_Codigo] = _nsaPUC_GL10000.PropertyNames.Nsa_Descripcion_Codigo;
					ht[DEX_ROW_ID] = _nsaPUC_GL10000.PropertyNames.DEX_ROW_ID;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string Nsa_Nivel_Cuenta = "Nsa_Nivel_Cuenta";
            public const string Nsa_Descripcion_Nivel = "Nsa_Descripcion_Nivel";
            public const string Nsa_Codigo = "Nsa_Codigo";
            public const string Nsa_Descripcion_Codigo = "Nsa_Descripcion_Codigo";
            public const string DEX_ROW_ID = "DEX_ROW_ID";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[Nsa_Nivel_Cuenta] = _nsaPUC_GL10000.ColumnNames.Nsa_Nivel_Cuenta;
					ht[Nsa_Descripcion_Nivel] = _nsaPUC_GL10000.ColumnNames.Nsa_Descripcion_Nivel;
					ht[Nsa_Codigo] = _nsaPUC_GL10000.ColumnNames.Nsa_Codigo;
					ht[Nsa_Descripcion_Codigo] = _nsaPUC_GL10000.ColumnNames.Nsa_Descripcion_Codigo;
					ht[DEX_ROW_ID] = _nsaPUC_GL10000.ColumnNames.DEX_ROW_ID;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string Nsa_Nivel_Cuenta = "s_Nsa_Nivel_Cuenta";
            public const string Nsa_Descripcion_Nivel = "s_Nsa_Descripcion_Nivel";
            public const string Nsa_Codigo = "s_Nsa_Codigo";
            public const string Nsa_Descripcion_Codigo = "s_Nsa_Descripcion_Codigo";
            public const string DEX_ROW_ID = "s_DEX_ROW_ID";

		}
		#endregion		
		
		#region Properties
	
		public virtual string Nsa_Nivel_Cuenta
	    {
			get
	        {
				return base.Getstring(ColumnNames.Nsa_Nivel_Cuenta);
			}
			set
	        {
				base.Setstring(ColumnNames.Nsa_Nivel_Cuenta, value);
			}
		}

		public virtual string Nsa_Descripcion_Nivel
	    {
			get
	        {
				return base.Getstring(ColumnNames.Nsa_Descripcion_Nivel);
			}
			set
	        {
				base.Setstring(ColumnNames.Nsa_Descripcion_Nivel, value);
			}
		}

		public virtual string Nsa_Codigo
	    {
			get
	        {
				return base.Getstring(ColumnNames.Nsa_Codigo);
			}
			set
	        {
				base.Setstring(ColumnNames.Nsa_Codigo, value);
			}
		}

		public virtual string Nsa_Descripcion_Codigo
	    {
			get
	        {
				return base.Getstring(ColumnNames.Nsa_Descripcion_Codigo);
			}
			set
	        {
				base.Setstring(ColumnNames.Nsa_Descripcion_Codigo, value);
			}
		}

		public virtual int DEX_ROW_ID
	    {
			get
	        {
				return base.Getint(ColumnNames.DEX_ROW_ID);
			}
			set
	        {
				base.Setint(ColumnNames.DEX_ROW_ID, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_Nsa_Nivel_Cuenta
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Nsa_Nivel_Cuenta) ? string.Empty : base.GetstringAsString(ColumnNames.Nsa_Nivel_Cuenta);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Nsa_Nivel_Cuenta);
				else
					this.Nsa_Nivel_Cuenta = base.SetstringAsString(ColumnNames.Nsa_Nivel_Cuenta, value);
			}
		}

		public virtual string s_Nsa_Descripcion_Nivel
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Nsa_Descripcion_Nivel) ? string.Empty : base.GetstringAsString(ColumnNames.Nsa_Descripcion_Nivel);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Nsa_Descripcion_Nivel);
				else
					this.Nsa_Descripcion_Nivel = base.SetstringAsString(ColumnNames.Nsa_Descripcion_Nivel, value);
			}
		}

		public virtual string s_Nsa_Codigo
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Nsa_Codigo) ? string.Empty : base.GetstringAsString(ColumnNames.Nsa_Codigo);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Nsa_Codigo);
				else
					this.Nsa_Codigo = base.SetstringAsString(ColumnNames.Nsa_Codigo, value);
			}
		}

		public virtual string s_Nsa_Descripcion_Codigo
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Nsa_Descripcion_Codigo) ? string.Empty : base.GetstringAsString(ColumnNames.Nsa_Descripcion_Codigo);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Nsa_Descripcion_Codigo);
				else
					this.Nsa_Descripcion_Codigo = base.SetstringAsString(ColumnNames.Nsa_Descripcion_Codigo, value);
			}
		}

		public virtual string s_DEX_ROW_ID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.DEX_ROW_ID) ? string.Empty : base.GetintAsString(ColumnNames.DEX_ROW_ID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.DEX_ROW_ID);
				else
					this.DEX_ROW_ID = base.SetintAsString(ColumnNames.DEX_ROW_ID, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter Nsa_Nivel_Cuenta
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Nsa_Nivel_Cuenta, Parameters.Nsa_Nivel_Cuenta);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Nsa_Descripcion_Nivel
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Nsa_Descripcion_Nivel, Parameters.Nsa_Descripcion_Nivel);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Nsa_Codigo
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Nsa_Codigo, Parameters.Nsa_Codigo);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Nsa_Descripcion_Codigo
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Nsa_Descripcion_Codigo, Parameters.Nsa_Descripcion_Codigo);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter DEX_ROW_ID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.DEX_ROW_ID, Parameters.DEX_ROW_ID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter Nsa_Nivel_Cuenta
		    {
				get
		        {
					if(_Nsa_Nivel_Cuenta_W == null)
	        	    {
						_Nsa_Nivel_Cuenta_W = TearOff.Nsa_Nivel_Cuenta;
					}
					return _Nsa_Nivel_Cuenta_W;
				}
			}

			public WhereParameter Nsa_Descripcion_Nivel
		    {
				get
		        {
					if(_Nsa_Descripcion_Nivel_W == null)
	        	    {
						_Nsa_Descripcion_Nivel_W = TearOff.Nsa_Descripcion_Nivel;
					}
					return _Nsa_Descripcion_Nivel_W;
				}
			}

			public WhereParameter Nsa_Codigo
		    {
				get
		        {
					if(_Nsa_Codigo_W == null)
	        	    {
						_Nsa_Codigo_W = TearOff.Nsa_Codigo;
					}
					return _Nsa_Codigo_W;
				}
			}

			public WhereParameter Nsa_Descripcion_Codigo
		    {
				get
		        {
					if(_Nsa_Descripcion_Codigo_W == null)
	        	    {
						_Nsa_Descripcion_Codigo_W = TearOff.Nsa_Descripcion_Codigo;
					}
					return _Nsa_Descripcion_Codigo_W;
				}
			}

			public WhereParameter DEX_ROW_ID
		    {
				get
		        {
					if(_DEX_ROW_ID_W == null)
	        	    {
						_DEX_ROW_ID_W = TearOff.DEX_ROW_ID;
					}
					return _DEX_ROW_ID_W;
				}
			}

			private WhereParameter _Nsa_Nivel_Cuenta_W = null;
			private WhereParameter _Nsa_Descripcion_Nivel_W = null;
			private WhereParameter _Nsa_Codigo_W = null;
			private WhereParameter _Nsa_Descripcion_Codigo_W = null;
			private WhereParameter _DEX_ROW_ID_W = null;

			public void WhereClauseReset()
			{
				_Nsa_Nivel_Cuenta_W = null;
				_Nsa_Descripcion_Nivel_W = null;
				_Nsa_Codigo_W = null;
				_Nsa_Descripcion_Codigo_W = null;
				_DEX_ROW_ID_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter Nsa_Nivel_Cuenta
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Nsa_Nivel_Cuenta, Parameters.Nsa_Nivel_Cuenta);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Nsa_Descripcion_Nivel
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Nsa_Descripcion_Nivel, Parameters.Nsa_Descripcion_Nivel);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Nsa_Codigo
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Nsa_Codigo, Parameters.Nsa_Codigo);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Nsa_Descripcion_Codigo
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Nsa_Descripcion_Codigo, Parameters.Nsa_Descripcion_Codigo);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter DEX_ROW_ID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.DEX_ROW_ID, Parameters.DEX_ROW_ID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter Nsa_Nivel_Cuenta
		    {
				get
		        {
					if(_Nsa_Nivel_Cuenta_W == null)
	        	    {
						_Nsa_Nivel_Cuenta_W = TearOff.Nsa_Nivel_Cuenta;
					}
					return _Nsa_Nivel_Cuenta_W;
				}
			}

			public AggregateParameter Nsa_Descripcion_Nivel
		    {
				get
		        {
					if(_Nsa_Descripcion_Nivel_W == null)
	        	    {
						_Nsa_Descripcion_Nivel_W = TearOff.Nsa_Descripcion_Nivel;
					}
					return _Nsa_Descripcion_Nivel_W;
				}
			}

			public AggregateParameter Nsa_Codigo
		    {
				get
		        {
					if(_Nsa_Codigo_W == null)
	        	    {
						_Nsa_Codigo_W = TearOff.Nsa_Codigo;
					}
					return _Nsa_Codigo_W;
				}
			}

			public AggregateParameter Nsa_Descripcion_Codigo
		    {
				get
		        {
					if(_Nsa_Descripcion_Codigo_W == null)
	        	    {
						_Nsa_Descripcion_Codigo_W = TearOff.Nsa_Descripcion_Codigo;
					}
					return _Nsa_Descripcion_Codigo_W;
				}
			}

			public AggregateParameter DEX_ROW_ID
		    {
				get
		        {
					if(_DEX_ROW_ID_W == null)
	        	    {
						_DEX_ROW_ID_W = TearOff.DEX_ROW_ID;
					}
					return _DEX_ROW_ID_W;
				}
			}

			private AggregateParameter _Nsa_Nivel_Cuenta_W = null;
			private AggregateParameter _Nsa_Descripcion_Nivel_W = null;
			private AggregateParameter _Nsa_Codigo_W = null;
			private AggregateParameter _Nsa_Descripcion_Codigo_W = null;
			private AggregateParameter _DEX_ROW_ID_W = null;

			public void AggregateClauseReset()
			{
				_Nsa_Nivel_Cuenta_W = null;
				_Nsa_Descripcion_Nivel_W = null;
				_Nsa_Codigo_W = null;
				_Nsa_Descripcion_Codigo_W = null;
				_DEX_ROW_ID_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_nsaPUC_GL10000Insert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.DEX_ROW_ID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_nsaPUC_GL10000Update]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_nsaPUC_GL10000Delete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.Nsa_Codigo);
			p.SourceColumn = ColumnNames.Nsa_Codigo;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.Nsa_Nivel_Cuenta);
			p.SourceColumn = ColumnNames.Nsa_Nivel_Cuenta;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Nsa_Descripcion_Nivel);
			p.SourceColumn = ColumnNames.Nsa_Descripcion_Nivel;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Nsa_Codigo);
			p.SourceColumn = ColumnNames.Nsa_Codigo;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Nsa_Descripcion_Codigo);
			p.SourceColumn = ColumnNames.Nsa_Descripcion_Codigo;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.DEX_ROW_ID);
			p.SourceColumn = ColumnNames.DEX_ROW_ID;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
