
// Generated by MyGeneration Version # (1.3.0.3)

using System;

namespace MVP.gpCustom
{
	public class GL00100 : _GL00100
	{
        public GL00100(string sConnectionString)
		{
            this.ConnectionString = sConnectionString;
        }
	}
}
