
// Generated by MyGeneration Version # (1.3.0.3)

using System;

namespace MVP.gpCustom
{
	public class GL00105 : _GL00105
	{
        public GL00105(string sConnectionString)
		{
            this.ConnectionString = sConnectionString;
		
		}
	}
}
