
// Generated by MyGeneration Version # (1.3.0.3)

using System;

namespace MVP.gpCustom
{
	public class nsaPUC_GL10000 : _nsaPUC_GL10000
	{
        public nsaPUC_GL10000(string sConnectionString)
		{
            this.ConnectionString = sConnectionString;

		}
	}
}
