
// Generated by MyGeneration Version # (1.3.0.3)

using System;

namespace MVP.gpCustom
{
	public class tii_mapeo_puc : _tii_mapeo_puc
	{
		public tii_mapeo_puc(string sConnectionString)
		{
		    this.ConnectionString = sConnectionString;
		}
        public int loadFromSqlNoExec (string sp)
        {
            return(this.LoadFromSqlNoExec(sp));
        }
	}
}
